//
// GetHealth429Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetHealth429Response: Codable, JSONEncodable, Hashable {

    public var error: ModelError?
    public var meta: Meta?
    public var success: Bool

    public init(error: ModelError? = nil, meta: Meta? = nil, success: Bool) {
        self.error = error
        self.meta = meta
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case meta
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encode(success, forKey: .success)
    }
}

