//
// GetV1RunnerModels200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetV1RunnerModels200ResponseData: Codable, JSONEncodable, Hashable {

    public var models: [String]?

    public init(models: [String]? = nil) {
        self.models = models
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case models
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(models, forKey: .models)
    }
}

