//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelError: Codable, JSONEncodable, Hashable {

    public var code: String
    public var details: AnyCodable?
    public var message: String

    public init(code: String, details: AnyCodable? = nil, message: String) {
        self.code = code
        self.details = details
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case details
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encode(message, forKey: .message)
    }
}

