//
// PostV1RunnerChatRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostV1RunnerChatRequest: Codable, JSONEncodable, Hashable {

    public var messages: [PostV1RunnerChatRequestMessagesInner]

    public init(messages: [PostV1RunnerChatRequestMessagesInner]) {
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messages, forKey: .messages)
    }
}

