//
// RunnerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RunnerAPI {

    /**
     List configured runner model routes
     
     - returns: GetV1RunnerModels200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getV1RunnerModels() async throws -> GetV1RunnerModels200Response {
        return try await getV1RunnerModelsWithRequestBuilder().execute().body
    }

    /**
     List configured runner model routes
     - GET /v1/runner/models
     - 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Reset(Int), X-Request-ID(String)]
     - returns: RequestBuilder<GetV1RunnerModels200Response> 
     */
    open class func getV1RunnerModelsWithRequestBuilder() -> RequestBuilder<GetV1RunnerModels200Response> {
        let localVariablePath = "/v1/runner/models"
        let localVariableURLString = LthnApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetV1RunnerModels200Response>.Type = LthnApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Multi-turn chat completion
     
     - parameter postV1RunnerChatRequest: (body)  
     - returns: PostV1RunnerChat200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postV1RunnerChat(postV1RunnerChatRequest: PostV1RunnerChatRequest) async throws -> PostV1RunnerChat200Response {
        return try await postV1RunnerChatWithRequestBuilder(postV1RunnerChatRequest: postV1RunnerChatRequest).execute().body
    }

    /**
     Multi-turn chat completion
     - POST /v1/runner/chat
     - 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Reset(Int), X-Request-ID(String)]
     - parameter postV1RunnerChatRequest: (body)  
     - returns: RequestBuilder<PostV1RunnerChat200Response> 
     */
    open class func postV1RunnerChatWithRequestBuilder(postV1RunnerChatRequest: PostV1RunnerChatRequest) -> RequestBuilder<PostV1RunnerChat200Response> {
        let localVariablePath = "/v1/runner/chat"
        let localVariableURLString = LthnApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postV1RunnerChatRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PostV1RunnerChat200Response>.Type = LthnApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Single-prompt generation
     
     - parameter postV1RunnerGenerateRequest: (body)  
     - returns: PostV1RunnerChat200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func postV1RunnerGenerate(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest) async throws -> PostV1RunnerChat200Response {
        return try await postV1RunnerGenerateWithRequestBuilder(postV1RunnerGenerateRequest: postV1RunnerGenerateRequest).execute().body
    }

    /**
     Single-prompt generation
     - POST /v1/runner/generate
     - 
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Reset(Int), X-Request-ID(String)]
     - parameter postV1RunnerGenerateRequest: (body)  
     - returns: RequestBuilder<PostV1RunnerChat200Response> 
     */
    open class func postV1RunnerGenerateWithRequestBuilder(postV1RunnerGenerateRequest: PostV1RunnerGenerateRequest) -> RequestBuilder<PostV1RunnerChat200Response> {
        let localVariablePath = "/v1/runner/generate"
        let localVariableURLString = LthnApiAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postV1RunnerGenerateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PostV1RunnerChat200Response>.Type = LthnApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
