//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SystemAPI {

    /**
     Health check
     
     - returns: GetHealth200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getHealth() async throws -> GetHealth200Response {
        return try await getHealthWithRequestBuilder().execute().body
    }

    /**
     Health check
     - GET /health
     - Returns server health status
     - responseHeaders: [X-RateLimit-Limit(Int), X-RateLimit-Remaining(Int), X-RateLimit-Reset(Int), X-Request-ID(String)]
     - returns: RequestBuilder<GetHealth200Response> 
     */
    open class func getHealthWithRequestBuilder() -> RequestBuilder<GetHealth200Response> {
        let localVariablePath = "/health"
        let localVariableURLString = LthnApiAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetHealth200Response>.Type = LthnApiAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
